### ISSUE TITLE
请问一下目前是还不支持QQ音乐VIP歌曲么 

### ISSUE THREAD

**Issue by qq1004273358** [iwxyi/NeveMusic#1]

**Comment by iwxyi** [comment]
嗯，暂时不支持

**Comment by qq1004273358** [comment]
感谢大佬百忙之中回复！
请问有考虑做vip音乐嘛？我刚买了两年绿钻，如果需要调试我可以给您cookie。
还有，请问您是否有交流反馈群呀？您的弹幕姬非常酷炫

---原始邮件---
发件人: "小乂"<notifications@github.com&gt;
发送时间: 2021年2月24日(周三) 下午4:32
收件人: "iwxyi/NeveMusic"<NeveMusic@noreply.github.com&gt;;
抄送: "qq1004273358"<1004273358@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [iwxyi/NeveMusic] 请问一下目前是还不支持QQ音乐VIP歌曲么  (#1)




 
嗯，暂时不支持

**Comment by iwxyi** [comment]
> 感谢大佬百忙之中回复！ 请问有考虑做vip音乐嘛？我刚买了两年绿钻，如果需要调试我可以给您cookie。 还有，请问您是否有交流反馈群呀？您的弹幕姬非常酷炫

还没有QQ群（其实本来也没想着会有人用），QQ音乐是用 [qq-music-api](https://github.com/rain120/qq-music-api) 这个库，应该是刚支持VIP的，但是我前一段时间测试的时候发现没效果，新版还没来得及测试。

**Comment by iwxyi** [comment]
刚刚建了QQ群：1038738410，欢迎来交流~
